name: run-check

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r tree-frame/build.requirements.txt
    - run: |
        cd tree-frame
        make check 